name = "hugo-theme"
license = "MIT"
licenselink = "https://github.com/davidrbingham/hugo-theme/blob/main/LICENSE"
description = "Basic Blog Theme"
homepage = "https://github.com/davidrbingham/hugo-theme"
tags = ["dark", "blog", "multilingual"]
features = ["posts", "dark", "related content", "multilingual"]
min_version = "0.1.0"

[author]
  name = "davidrbingham"
  homepage = "https://davidbingham.me"
